services:
  - docker

before_install:
- docker pull woodenfish42/hustoj-deb

script:
- docker run -v `pwd`/deb:/tmp/deb woodenfish42/hustoj-deb sh -c "cd /root/hustoj-0.0.1 && dpkg-buildpackage && mv /root/hustoj_0.0.1_amd64.deb /tmp/deb"

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - deb/hustoj_0.0.1_amd64.deb
  skip_cleanup: true
