Document: hustoj
Title: Debian hustoj Manual
Author: <insert document author here>
Abstract: This manual describes what hustoj is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/hustoj/hustoj.sgml.gz

Format: postscript
Files: /usr/share/doc/hustoj/hustoj.ps.gz

Format: text
Files: /usr/share/doc/hustoj/hustoj.text.gz

Format: HTML
Index: /usr/share/doc/hustoj/html/index.html
Files: /usr/share/doc/hustoj/html/*.html
